name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: sudo npm cache clean -f
      - run: sudo npm install -g n
      - run: sudo n stable
      - run: sudo npm install -g npm@10.2.5
      - run: sudo npm ci
      - run: sudo npm audit fix
      - run: sudo npm run build
